name: Java CI for Subdirectory with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'github-actions-spring-boot/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'github-actions-spring-boot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file github-actions-spring-boot/pom.xml

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./github-actions-spring-boot
        file: ./github-actions-spring-boot/Dockerfile
        push: false
        tags: your-dockerhub-username/your-repo-name:latest
