name: Java CI for Subdirectory with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'github-actions-spring-boot/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'github-actions-spring-boot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file github-actions-spring-boot/pom.xml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Build Docker image
      id: build-and-load
      uses: docker/build-push-action@v5
      with:
        context: ./github-actions-spring-boot
        file: ./github-actions-spring-boot/Dockerfile
        push: false
        load: true
        tags: prkrb01/github-actions:${{ github.sha }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Registry
      run: docker push ${{ steps.build-and-load.outputs.tags }}
